# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-mich2021-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.0
  - macs2=2.2.7
  - star=2.5.3
  - samtools=1.3
  - bowtie2=2.3.5
  - igvtools=2.5.3
  - bedtools=2.29.2
  - trim-galore=0.6.2
  - homer=4.11.0
  - ucsc-wigToBigWig=377
